# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.
version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 100
  reviewers:
  - planetf1
  - wbittles
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 25
  reviewers:
  - planetf1
